try to fix release-prep on CCI (#556)

diff --git a/scripts/release-prep b/scripts/release-prep
--- a/scripts/release-prep
+++ b/scripts/release-prep
@@ -21,11 +21,29 @@ if [ "$INCREMENT_TYPE" == "" ]; then
       exit 1
 fi
 
-# Merge Changes
-yarn run merge-ci
+if [ "$SOURCE_BRANCH" != "$CIRCLE_BRANCH" ]; then
+    echo "ERROR: configuration should be run on the branch that contains the changes (usually main)"
+    exit 1
+fi
 
-# Check out release branch
+# Merge Changes
+if ! git show-ref --quiet $RELEASE_BRANCH; then
+    echo "Creating release branch:" $CREATE_RELEASE_BRANCH
+    if [ "$CREATE_RELEASE_BRANCH" == "true" ]; then
+        echo "Creating $RELEASE_BRANCH"
+        git checkout -b $RELEASE_BRANCH
+        git push --set-upstream origin $RELEASE_BRANCH
+    else
+        echo "ERROR: release branch does not exist"
+        exit 1
+    fi
+fi
+
+# initial merge with "ours" strategy to auto-resolve conflicts
+git checkout $SOURCE_BRANCH
+git pull origin $RELEASE_BRANCH --no-rebase -s ours
 git checkout $RELEASE_BRANCH
+git merge --no-edit $SOURCE_BRANCH
 
 # Set Release Version
 yarn run set-release-versions-ci
